---
# main playbook file

- name: ansible-tutorial (playbook)
  hosts: localhost

  tasks:
   
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
      tags:
        - reboot_server
...
